name: RUN NOTEBOOK

on:
  workflow_dispatch:
    inputs:
      name:
        description: "NOTEBOOK NAME (ví dụ: binary/synt_test)"
        required: true
        default: ""

permissions:
  contents: write # để commit & push

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install jupyter nbconvert

      - name: Run notebook ${{ github.event.inputs.name }}
        run: |
          set -e
          NB_PATH="experiments/${{ github.event.inputs.name }}.ipynb"
          NB_DIR="$(dirname "$NB_PATH")"
          NB_BASE="$(basename "$NB_PATH" .ipynb)"
          jupyter nbconvert --to notebook --execute "$NB_PATH" \
            --output "$NB_BASE" \
            --output-dir "$NB_DIR"

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add "experiments/${{ github.event.inputs.name }}.ipynb"
          git commit -m "Update notebook results [skip ci]" || echo "No changes to commit"
          git push
